#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: JESTARH EDUCATION ASSISTANCE PROGRAM
org_name_abbrev: JEAP
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  JEAP is a registered grassroot, community-based nonprofit dedicated to helping vulnerable children stay in school, learn with dignity, and build a brighter future.

org_full_description: >
  JESTARH Education Assistance Program (JEAP) is a registered grassroots community-based nonprofit organization with headquarters in Shisong, Bui Division, in the Northwest Region of Cameroon.

  Through our integrated approach of providing essential school materials, supporting teachers, improving school infrastructure, and empowering parents and families to take an active role in their children's education, we strive to address the everyday barriers that prevent children from learning and improve access to quality education.

  By working closely with schools, community leaders, and local families, we ensure that our solutions are practical, sustainable, and rooted in the needs of the communities we serve.

  At JEAP, we believe that every child deserves the opportunity to learn, grow, and build a brighter future; and we are dedicated to making that a reality.

org_mission: "To support the education needs of children, teachers, and schools in our communities by making quality learning more accessible by providing essential school materials, improving learning spaces, and offering guidance and support to children and their families."

org_vision: "A future where every child has an equal chance to learn, grow, and build a brighter future."

#OPTIONAL
org_general_email_inbox: jeapjoannursery@gmail.com
org_street_address: Kumbo
org_address_suite: Bui Division
org_city: North West Region
org_state: Cameroon
org_zip:
org_phone_cmr: >
  (237) 679-023-889
org_phone_tky: >
  (90) 536-742-24-58
org_phone_uk: >
  (44) 7846-189-230
org_phone_usa: >
  (1) 806-731-7656

#SOCIAL MEDIA
org_twitter_username: smartergiving
org_facebook_username: smartergiving
org_instagram_username:

#TAX STATUS
fiscal_sponsor: false
fiscal_sponsor_name:
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
donorbox_campaign_name: jeap-education-fund
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
publish: false

#COLOR SCHEME
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: assets/_sass
  style: compressed

#Features under development
paypal_button_id:
smartergiving_id:
